https:
  port: "8081"
api:
  id: "16176135"
  base: "api"
  semantic:
    version: "v1"
  port: "8092"
json:
  logger:
    disabledFields: ""
    prettyPrint: "false"
    locationInfo: "true"
    # Modify timestamp dateformat / timezone
    # - DateTime: Defaults to ISO format
    # - TimeZone: Defaults to UTC. Refer to https://en.wikipedia.org/wiki/List_of_tz_database_time_zones for valid timezones
    #dateformat: "yyyy-MM-dd HH:mm:ss.SSS"
    #timezone: "US/Eastern"
    application:
      name: "8db5810f-1022-47cc-856e-2156f651647f"
      version: "1.0.0"
multiTenantRouter:
  accessKey: "![UaROhf8YKMabaGvv8ia3g8OPDlGp0YmC3tQHl8O9TlU=]"
  secretKey: "![K0isSCb6S/mrrnrIBrIJCyp3vJTiND4VUu83x+9CU0JAQwN8HgncpEaWjqIZcSwD]"
  region: "us-west-2"
  masterTable: "dev2-tenants-catalog"
  
admin:
  host: "saas-api-dev2.s37dev.com"
  port: "443"
  basePath: "/platform"