https:
  port: "8081"
api:
  id: "15847883"
  base: "api"
  semantic:
    version: "v1"
  port: "8092"
json:
  logger:
    disabledFields: ""
    prettyPrint: "false"
    locationInfo: "true"
    # Modify timestamp dateformat / timezone
    # - DateTime: Defaults to ISO format
    # - TimeZone: Defaults to UTC. Refer to https://en.wikipedia.org/wiki/List_of_tz_database_time_zones for valid timezones
    #dateformat: "yyyy-MM-dd HH:mm:ss.SSS"
    #timezone: "US/Eastern"
    application:
      name: "8db5810f-1022-47cc-856e-2156f651647f"
      version: "1.0.0"
#database:
#  user: "admin"
#  password: "n0r4123!"
#  host: "db-nora-dev.cti10lnrh4rb.us-west-2.rds.amazonaws.com"
#  port: "3306"
#  schema: "trial"
multiTenantRouter:
  accessKey: "![tl+wk60a490r9OYeNjgHTh1uda8N940E+Aj1bGrKC78=]"
  secretKey: "![ZKJluEMpR9TszbML8jmgZE1x6pi8Fv8yCgasXawDscqzhqzQsNOB8IYM6oEd2RoF]"
  region: "us-west-2"
  masterTable: "dev-mulesoft-catalog-table"
